### ISSUE TITLE
Provide ByteBuffer interface that allow using Direct Buffer

### ISSUE THREAD

**Issue by mingfai** [niwibe/jnanomsg#6]
it's desirable for Java network library to provide ByteBuffer in addition to (or rather than) byte[] interface that works with direct buffer. Direct buffer resides outside JVM heap, the following are two examples that using ByteBuffer will help:
  - sending out bytes that are just received, there will be no need to copy data between the JVM
  - using memory mapped serialization/encoding libraries (i.e. Google FlatBuffers and Simple Binary Encoding). Those libraries allow access to fields directly in ByteBuffer.  

JNA supports direct buffer. The code is simple:
```java
    public synchronized ByteBuffer recvByteBuffer() throws IOException {
        final PointerByReference ptrBuff = new PointerByReference();

        final int socket = getNativeSocket();
        final int received = NativeLibrary.nn_recv(socket, ptrBuff, Nanomsg.constants.NN_MSG, 0);
        if (received < 0) {
            final int errno = Nanomsg.getErrorNumber();
            final String msg = Nanomsg.getError();
            throw new IOException(msg, errno);
        }

        final Pointer result = ptrBuff.getValue();
        final ByteBuffer bytesResult = result.getByteBuffer(0, received); // <--- Watch this line

        NativeLibrary.nn_freemsg(result);
        return bytesResult;
    }
```

The above code does work... mostly... for some reasons, it doesn't work 100%, sometimes the direct buffer bytes seems to be shifted. I'll take care of this issue when I have time to revisit and figure out what goes wrong.

**Comment by niwibe** [comment]
This is already implemented in master.

Thanks for you code snippets!
